--DATABASE CREATION
DROP DATABASE IF EXISTS teams_db;
CREATE DATABASE teams_db;
USE teams_db;

--DEPARTMENT CREATION
    CREATE TABLE departments (
id INT NOT NULL,
name VARCHAR (100) NOT NULL
    )

--ROLE CREATION


--EMPLOYEE CREATION